### ISSUE TITLE
on play player skips through list

### ISSUE THREAD

**Issue by mediaformat** [gillesdemey/Cumulus#89]
Cumulus v0.10.0 on macOS 10.11.6

After login I can see my feed. 

As soon as I try to play anything, the player just skips through everything, loading all track metadata into the player (.

**Comment by Hum4n01d** [comment]
I'm getting a similar issue

**Comment by mediaformat** [comment]
tried v.0.9.0, same deal

**Comment by Hum4n01d** [comment]
I’m using v0.9.0 and it’s skipping through, how should I fix this? /cc @gillesdemey

**Comment by Hum4n01d** [comment]
This might be helpful @gillesdemey:

I ran with `NODE_ENV=development` and got a whole bunch errors in the console that said:

`https://api.soundcloud.com/tracks/224674551/stream?client_id=f17c1d67b83c86194fad2b1948061c9e 429 (Unknown)`

I checked one of the error pages and I saw this:

`{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":15000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2017/03/12 12:22:59 +0000"}}]}`

It looks like there’s rate limiting stopping Cumulus from working. :(

**Comment by gillesdemey** [comment]
I think it's pretty obvious at this point that Cumulus' application credentials are exceeding the 15.000 plays / 24h rate limit.

https://developers.soundcloud.com/docs/api/rate-limits

I'm not quite sure if we can increase the rate limit, so at this point all we can do is show some sort of exception to the user 😔

**Comment by Hum4n01d** [comment]
ok :)

**Comment by mirshko** [comment]
@gillesdemey I too am having this issue. I would escalate this issue to critical bug. 

I hope SoundCloud doesn't give you guys the Twitter dev treatment.

**Comment by dougos** [comment]
Having the same issue, making Cumulus unusable.

**Comment by benjaminclark** [comment]
I used to use soundnode and then I switched to cumulus because it ran into the same rate-limiting problem. Back on the hunt. Thank you to the devs for making such an insanely beautiful and minimal app. I will miss it. My productivity will miss it. Purple heart :purple_heart: much love, respect :v:

**Comment by gillesdemey** [comment]
Thanks for the kind words @benjaminclark. 

I've requested to have the API rate limit increased, waiting to hear back from them 🤞

**Comment by mediaformat** [comment]
otherwise a few api keys could be used, and switch between them on rate-limit error

**Comment by MichielDeMey** [comment]
@mediaformat We've discussed this approach internally and we're not going to go down this road since this goes against their Terms of User.
See: https://developers.soundcloud.com/docs/api/terms-of-use#quotas

As much as we'd like to, as an open-source community we have the obligation to play by the rules. 😉

**Comment by mediaformat** [comment]
ok, I hadn't seen that page! 

Fairplay to you guys :1st_place_medal:

**Comment by Hum4n01d** [comment]
Dang

**Comment by FoxxMD** [comment]
😢

**Comment by seppestas** [comment]
Should we start some sort of petition? I'm thinking some kind of link to retweet a tweet to Soundcloud or something?

**Comment by afischer** [comment]
Would someone with the know-how be interested in writing a how-to build from source with your own API key?

Also—would it be possible to add an "API Key" field somewhere in settings so users could use their own without having to build from source? Or would that also be a TOS violation?

**Comment by gillesdemey** [comment]
> Also - would it be possible to add an "API Key" field somewhere in settings so users could use their own without having to build from source?

Seems like quite the hassle, SoundCloud now requires users to request API credentials through a form (and it might take up to a month for them to get back to you).

**Comment by araphiel** [comment]
@afischer 

If you have Yarn installed:

`git clone https://github.com/gillesdemey/Cumulus.git && cd Cumulus`
`open app/js/app.js` & replace the client_id on line 47.
`yarn outdated`
`yarn upgrade [insert all listed dependencies from above.]`
`yarn`
`grunt build`

**Comment by afischer** [comment]
@araphiel — Thanks. Guess I need to apply and wait a month for credentials 🙄 

Not to get off topic but SC really needs to find a way to make some money... It would really be a shame to see them go under.

**Comment by jsphpl** [comment]
In the mean time, just copy the client_id from your browser's dev tools (visiting soundcloud.com) and apply it using the approach described by the @araphiel.

<img width="1005" alt="screen shot" src="https://cloud.githubusercontent.com/assets/5419165/24876030/67e20bec-1e2a-11e7-942d-0a80aa4ae666.png">

**Comment by Zarlex** [comment]
In the meantime you can give this alternative SoundCloud player a try :) https://cloud-player.io It also ships a native desktop app for Windows and Mac
Code is open source available [here](https://github.com/Cloud-Player/web) and build with Angular2

**Comment by jsphpl** [comment]
@Zarlex how do you tackle the rate limit problem?

**Comment by Zarlex** [comment]
So far the app is not used by many people so i'm not exceeding the 15000 requests/day :)

**Comment by ignaty** [comment]
Having same issue. 😞

**Comment by pioul** [comment]
I had a similar experience as @araphiel: it took SoundCloud a couple weeks to process the form and issue API keys for me to use in a custom build – looking forward to using Cumulus again!

**Comment by shyam-habarakada** [comment]
Combining suggestions from @araphiel and @jsphpl we have an easy workaround. To re-cap,

1. `git clone https://github.com/gillesdemey/Cumulus.git && cd Cumulus`
2. Navigate to soundcloud.com in your browser and grab your client_id from the developer tools network panel. You can see it in API calls like `https://api.soundcloud.com/e1/me/track_likes/ids?limit=5000&linked_partitioning=1&client_id=YOUR-CLIENT-ID-SHOULD-BE-SHOWN-HERE&app_version=1495114752`
3. open `app/js/app.js` & replace the `client_id` on line 47 with your soundcloud client_id
4. `yarn upgrade` 
5. `yarn`
6. `grunt build`
7. Run your locally built app

**Comment by MarkehMe** [comment]
@shyam-habarakada is there a build step missing? I'm getting `Error: Cannot find module 'electron-settings'
`

```
Uncaught Exception:
Error: Cannot find module 'electron-settings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/markhughes/src/Cumulus/dist/Cumulus-darwin-x64/Cumulus.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/markhughes/src/Cumulus/dist/Cumulus-darwin-x64/Cumulus.app/Contents/Resources/app/index.js:12:22)
    at Object.<anonymous> (/Users/markhughes/src/Cumulus/dist/Cumulus-darwin-x64/Cumulus.app/Contents/Resources/app/index.js:135:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

**Comment by zachmoody** [comment]
@MarkehMe I'm on OSX and got around that by downgrading NPM to 4.6.1. No idea why that works or if it's good practice.

**Comment by star114** [comment]
@markhughes 
Did you fix it?
I’m in the same problem.

**Comment by anitricks** [comment]
I had the same problem as @markhughes 

So I did mine with `npm` because `yarn` was giving me issues

install everything with `npm install`
but install electron-settings module version 2.2.2 
so do `npm install electron-settings@2.2.2`
and then build with `grunt build`
it should work 

I used the latest npm and grunt and every other module was the latest as well.

**Comment by FoxxMD** [comment]
For anyone coming across this thread @anitricks steps still work but there's no need for the electron settings anymore. @gillesdemey bumped the settings version and it just works now.

* Follow steps 1-3 from the [above comment](https://github.com/gillesdemey/Cumulus/issues/89#issuecomment-302515199)
* install with `npm install`
* `grunt build`
* Run the app from the `dist` directory 👍

**Comment by star114** [comment]
There is still something wrong with "yarn", not "npm".

The dependency of this project is managed by "yarn" officially, but if you install the dependencies with ```yarn``` and ```grunt build```, you get the same electron-settings error as @markhughes commented.

```npm install``` is ok.

**Comment by Radu-Raicea** [comment]
Might be worth putting @shyam-habarakada's solution in the README for now.

**Comment by colinfran** [comment]
is there an updated temporary solution to this? none of the previous temporary solutions are no longer working for me

**Comment by markhughes** [comment]
@colinfran all we can do is use our own keys - not the one that are provided

**Comment by gguman** [comment]
Can anyone help with installation pls. I got a lot of errors while trying to install it

**Comment by seppestas** [comment]
> Can anyone help with installation pls. I got a lot of errors while trying to install it

No-one will be able to help you with that description. This issue is about the app being rate limited by the Soundcloud APIs. Do you suspect your issue is something similar?

If not, I suggest creating a new issue with a more detailed description and error log, but even then I don't know if anyone is still actively supporting this app.

**Comment by gguman** [comment]
> > Can anyone help with installation pls. I got a lot of errors while trying to install it
> 
> No-one will be able to help you with that description. This issue is about the app being rate limited by the Soundcloud APIs. Do you suspect your issue is something similar?
> 
> If not, I suggest creating a new issue with a more detailed description and error log, but even then I don't know if anyone is still actively supporting this app.

Thanks for the answer. I went through the above installation process but there are dependency issues - fs-xattr. Both npm and yarn have the same problems for me if I use the latest version of them. What version of software should I use to successfully build the app? Can someone make a video of the process that will help people? This app is perfect among others and I still haven't found any alternatives. It is very frustrating that it is not supported

**Comment by gguman** [comment]
The application with node#11.15.0 was successfully built, but changing the client_id inside the file does not help - "Sorry, something went wrong" appears on any tabs. Also I noticed that now soundcloud works with api_v2. Maybe this is the problem? Is anyone using this app now?
